# Generated by Django 6.1.1 on 2026-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_note_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
